name: Docker_Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]


jobs: 
  build:
    runs-on: windows-latest
     
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          python-version: '3.x'
          
      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: maramayari/mayari:${GITHUB_SHA::8}
          outputs: type=docker,dest=/tmp/docker-s2-python.tar

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME}}/mayari:${GITHUB_SHA::8}
