name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and export
      uses: docker/build-push-action@v3
      with:
        context: .
        tags: wfajraoui/docker-s2-python:${GITHUB_SHA::8}
        outputs: type=docker,dest=/tmp/docker-s2-python.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-s2-python
        path: /tmp/docker-s2-python.tar

    - name: Save Docker Image for Stage Deploy
      run: docker save wfajraoui/docker-s2-python:${GITHUB_SHA::8} > /tmp/docker-s2-python.tar
    - name: Show /tmp
      run: ls -la /tmp
    
   
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-s2-python
        path: /tmp
      
    - name: Load image
      run: |
        docker load --input /tmp/docker-s2-python.tar
        docker image ls -a
    - name: Push Docker Image to Docker Hub
      run: docker push ${{secrets.DOCKER_USERNAME}}/docker-s2-python:${GITHUB_SHA::8}
